### ISSUE TITLE
IntranetUserJS: Set defaults for Koha fields and checkboxes

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/koha-plugin-intranetjs-set-defaults#1]
IntranetUserJS: Set defaults for Koha fields and checkboxes

Testaus:

Poista käytöstä seuraavat rimpsut nextillä

Laita raksi "Poista käsin poistettujen varausten maksut" -kohtaan palautuksessa
Asiakkaalle lähtevien ilmoitusten oletuskielivalinta suomeksi.
Laita niteiden eräpoistossa raksi kohtaan "Poista tietueet, jos kaikki niteet poistettu".
Kausijulkaisujen vastaanoton oletuskirjastoksi kirjautumiskirjasto (Tämä taitaa olla vain Vaarassa).

Aktivoi plugin ja määrittele sen asetuksiin, mitä rimpsua halutaan käyttää.

Kokeile, että valinta lisää halutun toiminnon virkailijaliittymään. Ilmoittakaa tähän tikettiin, jos jokin noista pluginin lisäämistä js-rimpsuista ei toimi halutulla tavalla.

**Comment by pknuuti** [comment]
Mitenkähän tämän kanssa oikein on: "Laita raksi "Poista käsin poistettujen varausten maksut" -kohtaan palautuksessa.
Tällä estetään noutamattoman varauksen maksun syntyminen, kun noudettavissa oleva varaus poistetaan palautuksen kautta.
Huom! Ei toimi, jos palautus tehdään muualla kuin Palautus-sivulla." Poistin varauksen nimenomaan Palautus-sivulla ja maksu syntyi asiakkaalle. Eikös sen varauksen voisi poistaa mieluummin asiakkaan sivulla?

**Comment by pknuuti** [comment]
Muut valinnat toimii mun testauksen mukaan niin kuin pitääkin.

**Comment by Kati-Helle** [comment]
Helle-nextissä toimivat nämä testaamani:
Asiakkaalle lähtevien ilmoitusten oletuskielivalinta suomeksi.
Laita niteiden eräpoistossa raksi kohtaan "Poista tietueet, jos kaikki niteet poistettu".

Helle-nextissä on piilotettu noudettavana olevan varauksen poistamismahdollisuus palautus-popparista, joten tätä en testannut:
Laita raksi "Poista käsin poistettujen varausten maksut" -kohtaan palautuksessa

Hellessä ei ole käytössä tätä, joten tämäkin jäi testaamatta
Kausijulkaisujen vastaanoton oletuskirjastoksi kirjautumiskirjasto (Tämä taitaa olla vain Vaarassa).

**Comment by AnneliO** [comment]
> Mitenkähän tämän kanssa oikein on: "Laita raksi "Poista käsin poistettujen varausten maksut" -kohtaan palautuksessa. Tällä estetään noutamattoman varauksen maksun syntyminen, kun noudettavissa oleva varaus poistetaan palautuksen kautta. Huom! Ei toimi, jos palautus tehdään muualla kuin Palautus-sivulla." Poistin varauksen nimenomaan Palautus-sivulla ja maksu syntyi asiakkaalle. Eikös sen varauksen voisi poistaa mieluummin asiakkaan sivulla?

Testasin tätä siili-nextillä niin, että poistin ensin palautusasetusten piilotuksen, jotta näin, mitä on valittuna ja mitä ei. Sitten poistin IntranetUserJS:stä tuota vastaavan JS-rimpsun. Palautusasetukseen ei tullut tätä valintaa ennen kuin aktivoin JS-liitännäisen:

![kuva](https://github.com/user-attachments/assets/4bc633f3-5bae-413b-923f-f6e2cc73ecba)

Testasin varauksen poistoa ennen liitännäisen aktivointia ja sen jälkeen. Ennen aktivointia asiakkaalle muodostui noutamattoman varauksen maksu, kun palautin noudettavissa olevan niteen ja valitsin popparista _Peruuta varaus_. Aktivoinnin jälkeen tuli tosiaan tuo rasti paikoilleen ja noutamattoman varauksen maksua ei syntynyt, kun valitsin nidettä palautettaessa, että noudettavissa oleva varaus poistetaan.

Minusta se siis toimii.

Tuo asetuksen valintapakotus tehtiin aikanaan siksi, että jostain syystä virkailijat halusivat poistaa varauksen palautuksessa, eikä esim. asiakkaan tiedoissa tai varausjonossa. Olisivatko asiakkaat marssineet tiskille varauksensa kanssa ja sanonut, että en tarvitse tätä. Helpoin reitti oli palauttaa nide ja valita _Peruuta varaus_. Siitä kuitenkin syntyy noutamattoman varauksen maksu, jos ei ole valittuna tuota "Poista käsin poistettujen varausten maksut" -kohtaa palautusasetuksissa, jonka vuoksi siihen on pakotettu rasti paikoilleen. Siinä on kuvauksen mukaisesti se "vika", että nuo asetukset ovat käytössä vain silloin, kun palautus tehdään Palautus-sivulla ollessa. Jos palautus tehdään vaikka yläreunan pikavalikosta, niin palautusasetukset eivät päde ja noutamattoman varauksen maksu syntyy. Tuota korvaamaan on myöskin olemassa piilotus koko Peruuta varaus -napille. Se on osa tätä rimpsuhirviötä, joka löytyy IntranetUserCSS-wikistä:

```
/* Piilota varauksen palauttamisen yhteydessä popparista Älä huomioi -nappi, noudettavana olevan varauksen palautuksen yhteydessä popparista Poista varaus -nappi ja Peru kuljetus -nappi. Käytössä on varausten automaattinen kiinni jääminen. */
body#circ_returns.circ.modal-open button.btn.btn-default { display: none; } 
body#circ_returns.circ.modal-open button.btn.btn-default.deny.cancel-hold { display: none; } 
body#circ_returns.circ.modal-open button.btn.btn-default.approve { display: initial; }
body#circ_returns.circ.modal-open button.btn.btn-default.print { display: initial; }
body#circ_returns.circ.modal-open button.btn.btn-default.deny { display: initial; }
body#circ_returns.circ.modal-open button.btn.btn-default.submit.openWin { display: initial; }
```

**Comment by AnneliO** [comment]
Reetalle tiedoksi, että palautin siili-nextillä tilanteen ns. alkutilaan, niin pääsette itse säätämään palikat sellaisiksi, kuin haluatte ne. :)

**Comment by pknuuti** [comment]
Kiitos Anneli, multa varmaan jäi huomaamatta se, että en ollut ottanut käyttöön tuota plugaria. Toimii nyt.

**Comment by MikkoLiimatainen** [comment]
Vaskissa ollut käytössä vain Asiakkaalle lähtevien ilmoitusten oletuskielivalinta suomeksi, mutta testasin nämä kaikki ja ne toimivat ymmärrykseni mukaan oikein.

**Comment by lmstrand** [comment]
Seuranta kimpoista. Kommentoi tikettiä, kun kunnossa omassa kimpassa:

- [x] Lappi
- [x] OUTI
- [x] Siili
- [x] Vaara
- [x] Lumme
- [x] Kyyti
- [x] Helle
- [x] Kirkes
- [x] Lastu
- [x] Vaski

**Comment by piiaseme** [comment]
OUTIssa testattu ja otettu käyttöön.

**Comment by LeenaKinnunen** [comment]
Lapissa laitettu nextille päälle plugarissa : Asiakkaalle lähtevien ilmoitusten oletuskielivalinta suomeksi. ja Laita niteiden eräpoistossa raksi kohtaan "Poista tietueet, jos kaikki niteet poistettu". Toimii. 

Kahta muuta sääntöä ei ole Lapilla käytössä.

**Comment by Kati-Helle** [comment]
> Helle-nextissä toimivat nämä testaamani: Asiakkaalle lähtevien ilmoitusten oletuskielivalinta suomeksi. Laita niteiden eräpoistossa raksi kohtaan "Poista tietueet, jos kaikki niteet poistettu".
> 
> Helle-nextissä on piilotettu noudettavana olevan varauksen poistamismahdollisuus palautus-popparista, joten tätä en testannut: Laita raksi "Poista käsin poistettujen varausten maksut" -kohtaan palautuksessa
> 
> Hellessä ei ole käytössä tätä, joten tämäkin jäi testaamatta Kausijulkaisujen vastaanoton oletuskirjastoksi kirjautumiskirjasto (Tämä taitaa olla vain Vaarassa).

Helle-nextissä toimivat edelleen.

**Comment by ElinaUotila** [comment]
Kirkesin nextillä olikin tämä jo määritelty, mutta en ole muistanut kommentoida. Joka tapauksessa näyttää toimivan.

**Comment by LastuJanneS** [comment]
Lastussa myös käytössä ja toimii

**Comment by AnneliO** [comment]
Kaikki kimpat ovat kuitanneet, joten suljen tiketin. :)
